In [1]:
import numpy as np

### dtype

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [3]:
arr1.dtype

dtype('float64')

In [4]:
arr2.dtype

dtype('int32')

### shorthand type code strings you can also use to refer to a dtype:

In [13]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([4128860, 6029375, 3801155, 5570652, 6619251, 7536754, 5701724,
       5374031], dtype=uint32)

## convert or cast an array from one dtype to another
Calling astype always creates a new array (a copy of the data), even
if the new dtype is the same as the old dtype.

### integer to float

In [6]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [7]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

### float to integer

If I cast some floating-point
numbers to be of integer dtype, the decimal part will be truncated:

In [8]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [9]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

### string to float

an array of strings representing numbers, you can use astype to convert
them to numeric form:

In [11]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

It’s important to be cautious when using the numpy.string_ type, as string data in NumPy is fixed size and may truncate input without warning. pandas has more intuitive out-of-the-box behav‐ ior on non-numeric data.

### use another array’s dtype attribute:

In [12]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])