In [2]:
import numpy as np

### one positive int_like arguments
If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

In [6]:
np.random.randn()

-0.5441194890433282

In [5]:
np.random.randn(2)

array([ 0.92374978, -0.1847438 ])

In [8]:
np.random.randn(4)

array([ 0.87014672, -1.25927908, -0.74292633,  0.14369958])

### 2 argument
Two-by-four array of samples from the normal distribution with
mean 3 and standard deviation 2.5:

In [9]:
np.random.randn(2, 4)

array([[ 0.54765706, -1.27051466,  0.9676148 ,  1.24488707],
       [-0.81943028,  0.09524449,  0.48980867, -0.43193684]])

In [10]:
3 + 2.5 * np.random.randn(2, 4)

array([[ 1.87573779,  7.33109132,  3.42311185,  0.34338631],
       [-3.21576121,  5.92111696,  4.73290133,  3.65345093]])

### 3 argument

In [12]:
np.random.randn(2,3,4)

array([[[-0.71320583, -0.06247769,  0.62716453, -0.03363389],
        [ 0.7128004 ,  1.32884969,  0.6270993 , -0.66172885],
        [-0.2455401 , -1.5236611 ,  1.93821883, -0.94461198]],

       [[ 0.60033453, -2.86671756, -1.26522515,  1.80195389],
        [-0.81584166,  2.14142794,  0.95824829,  2.84446243],
        [-0.44157575, -0.52311684, -0.64601173, -2.5336571 ]]])

### 4 argument

In [15]:
np.random.randn(2,2,3,4)

array([[[[-0.41416315, -0.63860356, -0.49835924, -1.47203877],
         [ 2.65460754,  0.28662029, -0.61488744, -0.91452   ],
         [-0.48514282, -1.36396651, -1.07169459, -0.08714886]],

        [[ 0.38836994,  0.45432231,  0.20992372, -0.97247646],
         [-1.93802331,  0.01485594,  0.59419866, -2.05737778],
         [ 0.82027446,  0.20403821,  0.88205956,  2.0741646 ]]],


       [[[-0.26034781,  1.1945209 , -1.23610686, -1.66190034],
         [-1.90688325, -0.5926771 , -0.16333258, -0.38596625],
         [-1.73878485, -0.3034155 , -0.51185323,  0.49462368]],

        [[-0.78381492, -0.81062958,  1.34924553, -1.24462462],
         [ 0.49231644, -0.57621188,  0.96144665, -0.99938706],
         [-1.83759579, -1.34783173, -1.23943092,  1.00650851]]]])

### for loop random

In [4]:
{i:np.random.randn(3) for i in range(3)}

{0: array([0.82174025, 1.21766137, 1.81256244]),
 1: array([-0.58650409, -0.96493081,  1.78991179]),
 2: array([ 1.52209248, -0.43295895, -0.17070986])}

In [3]:
{i:np.random.randn() for i in range(3)}

{0: -0.6575849318168522, 1: 0.517040827757146, 2: -0.7441672968224573}

### guide

In [7]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I