In [1]:
import numpy as np

## one dimension array

In [ ]:
np.arange(0, 5, 0.5, dtype=int)

In [ ]:
np.arange(-3, 3, 0.5, dtype=int)

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[5]

5

In [8]:
arr[5:8]

array([5, 6, 7])

In [33]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

### you assign a scalar value to a slice,

In [9]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### that array slices are views on the original array.
This means that the data is not copied, and any modifications to the view will be
reflected in the source array.

In [12]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [13]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [14]:
# The “bare” slice [:] will assign to all values in an array:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### If you want a copy of a slice of an ndarray instead of a view,

In [15]:
arr[5:8].copy()

array([64, 64, 64])

## two dimension array

I find it
helpful to think of axis 0 as the “rows” of the array and axis 1 as the “columns.”

In [37]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr2d[2]

array([7, 8, 9])

In [35]:
arr2d[0][2]

3

It can be helpful to read the expression arr2d[:2] as
“select the first two rows of arr2d.”

In [34]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

select the second row but only the first two columns

In [39]:
arr2d[1, :2]

array([4, 5])

select the third column but only the first two rows

In [40]:
arr2d[:2, 2]

array([3, 6])

Note that a colon by itself means to take the entire
axis, so you can slice only higher dimensional axes by doing:

In [41]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

assigning to a slice expression assigns to the whole selection:

In [42]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## the 2 × 2 × 3 array

In [21]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In multidimensional arrays, if you omit later indices, the returned object will be a
lower dimensional ndarray consisting of all the data along the higher dimensions.

In [22]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Both scalar values and arrays can be assigned to arr3d[0]:

In [23]:
old_values = arr3d[0].copy()

In [25]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### arr3d[1, 0] gives you all of the values whose indices start with (1, 0),
forming a 1-dimensional array:

In [28]:
arr3d[1, 0]

array([7, 8, 9])

### This expression is the same as though we had indexed in two steps:

In [30]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [31]:
x[0]

array([7, 8, 9])