In [2]:
import numpy as np

In [3]:
np.random.randint(5)

3

In [22]:
np.random.randint(2, size=10)

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 0])

In [23]:
np.random.randint(5, size=(2, 4)) # Generate a 2 x 4 array of ints between 0 and 4, inclusive

array([[1, 3, 0, 3],
       [0, 1, 0, 0]])

In [25]:
np.random.randint(1, [3, 5, 10]) # Generate a 1 x 3 array with 3 different upper bounds

array([2, 3, 4])

In [26]:
np.random.randint([1,10],20)

array([ 5, 16])

In [10]:
np.random.randint(1,[20,50])

array([ 5, 15])

In [17]:
np.random.randint(10,50,4) # từ 10 đến 50, 4 phần tử

array([16, 24, 35, 40])

In [4]:
data2 = np.random.randint(10,50,(2,4))
print(data2)

[[38 12 15 14]
 [46 44 15 12]]


In [5]:
data3 = np.random.randint(10,50,(2,2,2))
print(data3)

[[[37 28]
  [14 11]]

 [[43 34]
  [37 22]]]


In [28]:
# Generate a 2 by 4 array using broadcasting with dtype of uint8
np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)

array([[ 3,  8,  9,  8],
       [17,  8,  9,  7]], dtype=uint8)

In [3]:
np.random.randint([5, 5, 1, 1],[[10], [20]]) 

# GIẢI THÍCH
# [5, 5, 1, 1]: tạo mảng có 4 phần tử ngang
# [[10], [20]]: tạo mảng có 2 dòng
# kq:
# array([[a,b,c,d],       < 10
#        [x,y,z,v]])      < 20
# a,x >= 5
# b,y >= 5
# c,z >= 1
# d,v >= 1

array([[ 7,  9,  1,  1],
       [12, 11, 18,  3]])

In [4]:
np.random.randint([5, 5, 1, 1],[[10], [20],[8]])



array([[ 7,  8,  7,  7],
       [ 8, 13, 19,  1],
       [ 7,  5,  3,  2]])

In [5]:
np.random.randint([5, 5, 1, 1],[[10], [20],[8],[30]])

array([[ 9,  5,  7,  7],
       [ 6,  8, 11,  9],
       [ 6,  7,  5,  5],
       [21, 14, 10, 22]])

In [7]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp