In [1]:
import numpy as np

In [2]:
np.random.seed(0) ; np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [3]:
np.random.seed(0) ; np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

With the seed reset (every time), the same set of numbers will appear every time.

If the random seed is not reset, different numbers appear with every invocation:

In [5]:
np.random.rand(4)

array([0.4236548 , 0.64589411, 0.43758721, 0.891773  ])

In [7]:
np.random.rand(4)

array([0.96366276, 0.38344152, 0.79172504, 0.52889492])

(pseudo-)random numbers work by starting with a number (the seed), multiplying it by a large number, adding an offset, then taking modulo of that sum. The resulting number is then used as the seed to generate the next "random" number. When you set the seed (every time), it does the same thing every time, giving you the same numbers.

If you want seemingly random numbers, do not set the seed. If you have code that uses random numbers that you want to debug, however, it can be very helpful to set the seed before each run so that the code does the same thing every time you run it.

To get the most random numbers for each run, call numpy.random.seed(). This will cause numpy to set the seed to a random number obtained from /dev/urandom or its Windows analog or, if neither of those is available, it will use the clock